all:
	g++ DataAnalyserTests.cpp -o tests DataAnalyser.cpp FastExpSketch.cpp SketchKey.cpp -O3 -Wall -pedantic

playlist:
	g++ AnalysePlaylist.cpp -o analysePlaylist DataAnalyser.cpp FastExpSketch.cpp SketchKey.cpp -O3 -Wall -pedantic

profile:
	g++ AnalyseProfile.cpp -o analyseProfile DataAnalyser.cpp FastExpSketch.cpp SketchKey.cpp -O3 -Wall -pedantic